### ISSUE TITLE
die call in example

### ISSUE THREAD

**Issue by tomjn** [nekojira/wp-requirements#1] opened 2015-07-14 00:30 UTC
The example given in the readme if used would make it impossible to disable the plugin, and bring the site down. Any plugin with this check that triggers that was installed using the uploader or the .org repository will cripple the site it's used on

**Comment by unfulvio** [comment] 2015-07-14 05:21
Ah sorry actually you're right it should be `return;` and wow this was
fast... I only put this online few hours ago and went to sleep, was
planning to test it today, I wouldn't thought someone was already on it...
but thanks :)

**Comment by unfulvio** [comment] 2015-07-14 08:21
I reviewed the example in the readme as well as the class file and run a couple of tests, it looks fine now - what do you think?

I published this quietly yesterday and I'm surprised there were people on it after few hours :)

**Comment by tomjn** [comment] 2015-07-14 12:16
Great ^_^ if you can remove the `create_function` calls then it's perfect!

**Comment by unfulvio** [comment] 2015-07-14 12:51
I also dislike create_function to be honest... but the problem is... WP supports 5.2.4 which doesn't have anonymous functions. Ok I might tell people to create proper php functions, it'd just make the code lengthier than it should be. Would you have a more concise approach to this?

**Comment by tomjn** [comment] 2015-07-14 13:07
You could use an object to store and display the error messages, closures/anonymous functions aren't necesary

**Comment by unfulvio** [comment] 2015-07-14 14:06
well the class has a method for this `errors()` which returns an array of errors with keys matching where the version check didn't pass... but ok I think it's open for use in many ways, feel free to make any pull requests to the class or readme file or other improvements!

I'm closing this and thanks for pointing out the mistake

**Closed as completed by unfulvio** 2015-07-14 14:06 UTC

**Comment by unfulvio** [comment] 2015-07-15 08:53
meh! I did remove any reference to create_function, you're right it's just too evil and doesn't work well
